// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs0U6jsFtNAZ2EnbOY7Whqia4sBD1w8PM',
    appId: '1:298022819695:web:17d925d994897fedc2fa9a',
    messagingSenderId: '298022819695',
    projectId: 'learning-production-a10d2',
    authDomain: 'learning-production-a10d2.firebaseapp.com',
    storageBucket: 'learning-production-a10d2.appspot.com',
    measurementId: 'G-WLY23TXVNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB49hm8H2cDGXiOQ9FCvs2yc9WmKHwbls',
    appId: '1:298022819695:android:07a7e66ec1ca648bc2fa9a',
    messagingSenderId: '298022819695',
    projectId: 'learning-production-a10d2',
    storageBucket: 'learning-production-a10d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDnc_LVsaFYZbWJ38BSjDaTT96_XzrWS0',
    appId: '1:298022819695:ios:8a41dd2f9b0dcfa5c2fa9a',
    messagingSenderId: '298022819695',
    projectId: 'learning-production-a10d2',
    storageBucket: 'learning-production-a10d2.appspot.com',
    iosBundleId: 'com.personal.development',
  );
}
