// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCULWDeiJjh16dgWvAy2nDOZYa7JschT6w',
    appId: '1:323351798507:web:9487afd881731b396294ae',
    messagingSenderId: '323351798507',
    projectId: 'learning-development-edf0d',
    authDomain: 'learning-development-edf0d.firebaseapp.com',
    storageBucket: 'learning-development-edf0d.appspot.com',
    measurementId: 'G-2253FYCMSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZwIt6lC7dKXSbC9-SCWyDs5DWoIfw1E',
    appId: '1:323351798507:android:53bced5c22caa6c66294ae',
    messagingSenderId: '323351798507',
    projectId: 'learning-development-edf0d',
    storageBucket: 'learning-development-edf0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQwgZPEKYRzYU5uil3cC1oaHvh_A60Qhg',
    appId: '1:323351798507:ios:d89baa20a06881326294ae',
    messagingSenderId: '323351798507',
    projectId: 'learning-development-edf0d',
    storageBucket: 'learning-development-edf0d.appspot.com',
    iosBundleId: 'com.personal.development',
  );
}
