// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8F3GMltt5YyT0xN3XVOsUVFrmHRFzt8U',
    appId: '1:795585659872:web:389bd2b788268b30a22185',
    messagingSenderId: '795585659872',
    projectId: 'learning-production-c8ef7',
    authDomain: 'learning-production-c8ef7.firebaseapp.com',
    storageBucket: 'learning-production-c8ef7.appspot.com',
    measurementId: 'G-VH1MJLJDGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzWCQ662qOMBYVwAJGAjzbzJlbQWOswVw',
    appId: '1:795585659872:android:44fce06a12da50a8a22185',
    messagingSenderId: '795585659872',
    projectId: 'learning-production-c8ef7',
    storageBucket: 'learning-production-c8ef7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0nLdnmARVMvW9tkxpZgrxYLuiF4xO9FE',
    appId: '1:795585659872:ios:3b4edf9ae69da1d4a22185',
    messagingSenderId: '795585659872',
    projectId: 'learning-production-c8ef7',
    storageBucket: 'learning-production-c8ef7.appspot.com',
    iosBundleId: 'com.personal.development',
  );
}
