// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsMitT2N7aMpw7ubjFAu3LnolDh4Mrar0',
    appId: '1:766346609290:web:6d41214c694c2712356373',
    messagingSenderId: '766346609290',
    projectId: 'learning-staging-3ca9f',
    authDomain: 'learning-staging-3ca9f.firebaseapp.com',
    storageBucket: 'learning-staging-3ca9f.appspot.com',
    measurementId: 'G-9ENFKM07K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN8TCcwbAS1DGRdkJSaH_8JFe5reoeUHI',
    appId: '1:766346609290:android:b6dd88c02c01ada8356373',
    messagingSenderId: '766346609290',
    projectId: 'learning-staging-3ca9f',
    storageBucket: 'learning-staging-3ca9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCywtSMEL56uHIHip-RR1I2nz1NFLTOOYk',
    appId: '1:766346609290:ios:ac4357b4756f9471356373',
    messagingSenderId: '766346609290',
    projectId: 'learning-staging-3ca9f',
    storageBucket: 'learning-staging-3ca9f.appspot.com',
    iosBundleId: 'com.personal.development',
  );
}
