// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlRSwZew16VBbAYuSYYNnktT3UfgvYBIQ',
    appId: '1:610968252349:web:811c9abf360aa47d6f2cd4',
    messagingSenderId: '610968252349',
    projectId: 'learning-development-15fee',
    authDomain: 'learning-development-15fee.firebaseapp.com',
    storageBucket: 'learning-development-15fee.appspot.com',
    measurementId: 'G-LH81DDSJ6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS-MMSiLM0XPWZRQCnC0KLeDoNn-8tXJk',
    appId: '1:610968252349:android:347255aa6e8258ce6f2cd4',
    messagingSenderId: '610968252349',
    projectId: 'learning-development-15fee',
    storageBucket: 'learning-development-15fee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDepesWWWkWXL6G_CY82L5lDkkT_pX0CA0',
    appId: '1:610968252349:ios:cd678dab682bf5906f2cd4',
    messagingSenderId: '610968252349',
    projectId: 'learning-development-15fee',
    storageBucket: 'learning-development-15fee.appspot.com',
    iosBundleId: 'com.personal.dev',
  );
}
